### ISSUE TITLE
JSX - Creating multiple icons getting an error.

### ISSUE THREAD

**Issue by abhilashdonepudi** [adamlacombe/fa-icon#2]
Getting the following error by adding multiple fa-icon's in a single render function. Any insight into this issue ?

The JSX "fa-icon" element node should not be shared within the same renderer. The renderer caches element lookups in order to improve performance. However, a side effect from this is that the exact same JSX node should not be reused. For more information please see https://stenciljs.com/docs/templating-jsx#avoid-shared-jsx-nodes

Below is the code.

 render() {
    return  (
      <div>
        <fa-icon type="fas" name="star" size="medium" color="orange"></fa-icon>
        <fa-icon type="fas" name="star" size="medium" color="orange"></fa-icon>
        <fa-icon type="fas" name="star" size="medium" color="orange"></fa-icon>
        <fa-icon type="fas" name="star" size="medium" color="orange"></fa-icon>
        <fa-icon type="fas" name="star-half" size="medium" color="orange"></fa-icon>
      </div>
    );

**Comment by adamlacombe** [comment]
Can you wrap your code in `` ? Looks like your `render()` isn't returning anything.

Have you followed the suggestion in the [Stencil documentation](https://stenciljs.com/docs/templating-jsx#avoid-shared-jsx-nodes)?

> Alternatively, creating a factory function to return a common JSX node could be used instead since the returned value would be a unique instance


```typescript
@Component({
  tag: 'my-cmp',
})
export class MyCmp {

  surpriseIcon() {
    return <fa-icon type={'far'} name={'surprise'} size={'medium'} />;
  }

  mehIcon() {
    return <fa-icon type={'far'} name={'meh'} size={'medium'} />;
  }

  render() {
    return (
      <div>
        {this.surpriseIcon()}
        {this.surpriseIcon()}
        {this.mehIcon()}
        {this.mehIcon()}
      </div>
    );
  }
}
```
